name: "web_app"
mode: "dev"
port: 8080
start_time: "2021-07-01"
machine_id: 0
version: "1.0"

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "root"
  dbname: "sql_demo"
  max_open: 20
  max_idle: 20

redis:
  host: "127.0.0.1"
  port: 6379
  db: 0
  password: ""
  pool_size: 100
